package library_project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dubs
 */
public class OeuvreForm extends javax.swing.JFrame {

    private Statement state = Connexion.Connect().createStatement();
    String requete;
    ResultSet result;
    DefaultTableModel model;

    public OeuvreForm() throws SQLException, ClassNotFoundException {
        initComponents();
        findOeuvres(state);
    }


    public ArrayList<Oeuvre> ListOeuvres(String ValToSearch) {
        ArrayList<Oeuvre> oeuvresList = new ArrayList<Oeuvre>();

        try {
            
            String searchQuery = "SELECT * FROM oeuvre,category,langue ON category.id = oeuvre.id_category AND langue.id = oeuvre.id_langue WHERE  (titre`||`date_parution`||`note`)  LIKE '%" + ValToSearch + "%'";
            result = state.executeQuery(searchQuery);

            Oeuvre oeuvre;

            while (result.next()) {
                oeuvre = new Oeuvre(
                        result.getInt("id"),
                        result.getString("titre"),
                        result.getInt("date_parution"),
                        result.getString("commentaire"),
                        result.getInt("note")
                );
                oeuvresList.add(oeuvre);

            }
            return oeuvresList;


        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        return oeuvresList;

}

    // Filter Data In Jtable
    private void findOeuvres(Statement state) {
        ArrayList<Oeuvre> oeuvres = ListOeuvres(jTextField_Filter.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Id", "Titre", "Annee", "Commentaire", "Note"});
        Object[] row = new Object[5];

        for (int i = 0; i < oeuvres.size(); i++) {
            row[0] = oeuvres.get(i).getId();
            row[1] = oeuvres.get(i).getTitre();
            row[2] = oeuvres.get(i).getAnnee();
            row[3] = oeuvres.get(i).getCommentaire();
            row[4] = oeuvres.get(i).getNote();
            model.addRow(row);
        }
        jTable_Display_Oeuvres.setModel(model);


    }


    // Execute The Insert Update And Delete Querys
    public void executeSQlQuery(String query, String message) {

        try {

            if ((state.executeUpdate(query)) == 1) {
                // refresh jtable data
                DefaultTableModel model = (DefaultTableModel) jTable_Display_Oeuvres.getModel();
                model.setRowCount(0);
                model.fireTableDataChanged ();

                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
            findOeuvres(state);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Commentaire = new javax.swing.JTextField();
        jTextField_Titre = new javax.swing.JTextField();
        jTextField_Annee = new javax.swing.JTextField();
        jTextField_Id = new javax.swing.JTextField();
        jButton_Insert = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Oeuvres = new javax.swing.JTable();
        jTextField_Filter = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Note = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Id :");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Titre :");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Commentaire :");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Annee :");

        jTextField_Commentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CommentaireActionPerformed(evt);
            }
        });

        jTextField_Titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TitreActionPerformed(evt);
            }
        });

        jTextField_Annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AnneeActionPerformed(evt);
            }
        });

        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jButton_Insert.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Insert.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_Insert.setForeground(new java.awt.Color(0, 102, 0));
        jButton_Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_Insert.setText("INSERT");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Update.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Update.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_Update.setForeground(new java.awt.Color(0, 102, 204));
        jButton_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upd.png"))); // NOI18N
        jButton_Update.setText("UPDATE");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Delete.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_Delete.setForeground(new java.awt.Color(255, 0, 0));
        jButton_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        jButton_Delete.setText("DELETE");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jTable_Display_Oeuvres.setBackground(new java.awt.Color(204, 255, 255));
        jTable_Display_Oeuvres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titre", "Annee", "Commentaire", "Note"
            }
        ));
        jTable_Display_Oeuvres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_OeuvresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Oeuvres);

        jTextField_Filter.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jTextField_Filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_FilterKeyReleased(evt);
            }
        });

        jButton_Search.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton_Search.setText("SEARCH");
        jButton_Search.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Note :");

        jTextField_Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Insert)
                        .addGap(14, 14, 14)
                        .addComponent(jButton_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Delete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Titre, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jTextField_Annee)
                            .addComponent(jTextField_Commentaire)
                            .addComponent(jTextField_Note))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Insert)
                            .addComponent(jButton_Update)
                            .addComponent(jButton_Delete))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Search)
                            .addComponent(jTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_Commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jTextField_TitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TitreActionPerformed

    private void jTextField_AnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AnneeActionPerformed

    private void jTextField_CommentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CommentaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CommentaireActionPerformed

    private void jTable_Display_OeuvresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_OeuvresMouseClicked
        int i = jTable_Display_Oeuvres.getSelectedRow();
        TableModel model = jTable_Display_Oeuvres.getModel();
        jTextField_Id.setText(model.getValueAt(i, 0).toString());
        jTextField_Titre.setText(model.getValueAt(i, 1).toString());
        jTextField_Annee.setText(model.getValueAt(i, 2).toString());
        jTextField_Commentaire.setText(model.getValueAt(i, 3).toString());
        jTextField_Note.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable_Display_OeuvresMouseClicked

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        String query = "INSERT INTO `oeuvre`(`titre`,`date_parution`,`commentaire`,`note`) " +
                "VALUES ('" + jTextField_Titre.getText() + "','" + jTextField_Annee.getText() + "'," +
                "'" + jTextField_Commentaire.getText() + "','" + jTextField_Note.getText() + "')";
        executeSQlQuery(query, "Inserted");
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        String query = "UPDATE `oeuvre`SET `titre`= '" + jTextField_Titre.getText() + "'," +
                " `date_parution`= '" + jTextField_Annee.getText() + "', `commentaire`= '" +
                jTextField_Commentaire.getText() +"', `note`= '" + jTextField_Note.getText()  +
                "' WHERE `id`= '" + jTextField_Id.getText() + "'";
        executeSQlQuery(query, "Updated");
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        String query = "DELETE FROM `oeuvre` WHERE `id`= '" + jTextField_Id.getText() + "'";
        executeSQlQuery(query, "Deleted");
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTextField_FilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FilterKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FilterKeyReleased

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        findOeuvres(state);
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jTextField_NoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NoteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Oeuvres;
    private javax.swing.JTextField jTextField_Annee;
    private javax.swing.JTextField jTextField_Commentaire;
    private javax.swing.JTextField jTextField_Filter;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Note;
    private javax.swing.JTextField jTextField_Titre;
    // End of variables declaration//GEN-END:variables

}
